###
#
# This action needs a proper node and pnpm setup before!
#
# If you need to do some changes in a local-action used in this
# workflow, make sure you change the action-flag to your working
# branch-name to get the latest action functionality.
#
# Example: swisspost/design-system/.github/actions/setup-pnpm@my-working-branch-name
#
# Don't forget to change the action-flag back to 'main',
# once you have finished your work on the local-action!
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
###

name: Deploy to Netlify
description: Deploys dist folder to Netlify. Make sure you set up node and pnpm before!

inputs:
  netlify_auth_token:
    description: Netlify personal-access-token for use in shell scripts and API access.
    required: true
  netlify_site_id:
    description: Netlify site-id
    required: true
  event_number:
    description: The build output github_event_number
    required: true
  folder:
    description: Path to the folder to deploy
    required: true

outputs:
  url_alias:
    description: The url alias
    value: ${{ steps.netlify_deploy.outputs.alias }}

runs:
  using: composite
  steps:
    - name: Install netlify-cli
      shell: bash
      run: pnpm i -g netlify-cli
    - name: Deploy preview environment to netlify
      id: netlify_deploy
      shell: bash
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify_auth_token }}
      # run command taken from https://gist.github.com/oneohthree/f528c7ae1e701ad990e6, shortened to 28 chars, prepended with build-number
      run: |
        deploy_alias=`echo "preview-${{ inputs.event_number }}" | iconv -t ascii//TRANSLIT | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+\|-+$//g' | sed -E 's/^-+//g' | sed -E 's/-+$//g' | tr A-Z a-z`
        netlify link --id ${{ inputs.netlify_site_id }}
        netlify deploy --alias $deploy_alias --build false --dir ${{ inputs.folder }}
        echo "::set-output name=alias::$deploy_alias"
