###
#
# This action needs a proper node and pnpm setup before!
#
# If you need to do some changes in a local-action used in this
# workflow, make sure you change the action-flag to your working
# branch-name to get the latest action functionality.
#
# Example: swisspost/design-system/.github/actions/setup-pnpm@my-working-branch-name
#
# Don't forget to change the action-flag back to 'main',
# once you have finished your work on the local-action!
#
# https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions
#
###

name: Deploy to Netlify
description: Deploys dist folder to Netlify. Make sure you set up node and pnpm before!

inputs:
  id:
    description: The build id
    required: true
  action:
    description: The build action
    required: true
  github_token:
    description: Github access-token for use in shell scripts and API access.
    required: true
  netlify_auth_token:
    description: Netlify personal-access-token for use in shell scripts and API access.
    required: true
  netlify_site_id:
    description: Netlify site-id
    required: true
  netlify_site_url:
    description: The netlify base-url (incl. subdomain)
  folder:
    description: Path to the folder to deploy
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ inputs.folder }}
          production-branch: main
          github-token: ${{ inputs.github_token }}
          alias: preview-${{ inputs.id }}
          deploy-message: '🚀 Storybook Preview ready: https://preview-${{ inputs.id }}--${{ inputs.netlify_site_url }}'
          enable-pull-request-comment: true
          overwrites-pull-request-comment: true
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ inputs.netlify_auth_token }}
          NETLIFY_SITE_ID: ${{ inputs.netlify_site_id }}
        timeout-minutes: 1
