###
#
# Deploy a pre-built packages/styles storybook to netilfy
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Deploy Styles Storybook to Netlify
on:
  workflow_run:
    workflows: ['Build Styles Storybook']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: swisspost/design-system/.github/actions/setup-pnpm@main
      - uses: swisspost/design-system/.github/actions/artifact-download@main
        id: build
        with:
          name: design-system-styles-storybook
          folder: build-output

      - uses: swisspost/design-system/.github/actions/deploy-to-netlify@main
        id: deploy
        with:
          id: ${{ steps.build.outputs.id }}
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.STYLES_NETLIFY_SITE_ID }}
          folder: ${{ steps.build.outputs.folder }}

      - name: Comment on PullRequest
        uses: thollander/actions-comment-pull-request@v1
        # Only post the preview URL once per PR
        if: ${{ steps.build.outputs.action == 'opened' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This will comment on pull request with specific number
          pr_number: ${{ steps.build.outputs.id }}
          message: '🚀 Preview environment ready: https://${{ steps.deploy.outputs.url_alias }}--swisspost-design-system-styles.netlify.app'
