###
#
# Deploy a pre-built packages/styles storybook to netilfy
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Deploy Styles Storybook to Netlify
on:
  workflow_run:
    workflows: ['Build Styles Storybook']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: swisspost/design-system/.github/actions/setup-pnpm@main
      - uses: swisspost/design-system/.github/actions/artifact-download@main
        id: build
        with:
          name: design-system-styles-storybook
          folder: build-output

      - uses: actions/checkout@v3
      - name: Deploy to Netlify
          uses: nwtgck/actions-netlify@v1.2
          with:
            publish-dir: ${{ steps.build.outputs.folder }}
            production-branch: main
            github-token: ${{ secrets.GITHUB_TOKEN }}
            alias: preview-${{ steps.build.outputs.id }}
            deploy-message: '🚀 Storybook Preview ready: https://preview-${{ steps.build.outputs.id }}--swisspost-design-system-styles.netlify.app'
            enable-pull-request-comment: true
            overwrites-pull-request-comment: true
            enable-commit-comment: false
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.STYLES_NETLIFY_SITE_ID }}
          timeout-minutes: 1
